id: I7B11027E
ocr_import_info:
  timestamp: '2023-10-06T15:22:15.156078+00:00'
  batch_id: batch-7608
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharmakyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-10-06 15:32:56.747721+00:00
last_modified: 2023-10-06 15:32:56.747728+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W23164
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW23164
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བློ་སྦྱོང་གླེགས་བམ།
  languages:
  - bo
statistics:
  ocr_word_mean_confidence_index: 0.9683961184720351
  ocr_word_median_confidence_index: 0.99825126
bases:
  I0195:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0195
      total_pages: 586
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I0195.txt
    statistics:
      ocr_word_median_confidence_index: 0.99825126
      ocr_word_mean_confidence_index: 0.9683961184720351
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
